version: '2'
services:
   odoo:
        image: odoo:12.0
        depends_on:
            - postgres
        ports:
            - "8069:8069"
            - "8071:8071"
        environment:
            - HOST=postgres
            - USER=odoo
            - PASSWORD=odoo
        volumes:
            - ./config:/etc/odoo
            - ./repo:/opt/project
   postgres:
        image: postgres:10
        environment:
             - POSTGRES_DB=postgres
             - POSTGRES_PASSWORD=odoo
             - POSTGRES_USER=odoo
        volumes:
            - pg_data:/var/lib/postgresql/data
        restart: unless-stopped
volumes:
    pg_data:
